openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: swagger
tags:
  - name: Contacts
    description: Operation with contacts
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-kkxi.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/path/contacts/get.yaml'
    post:
      $ref: '../swagger/path/contacts/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/path/contacts/id/get.yaml'
    patch:
      $ref: '../swagger/path/contacts/id/patch.yaml'
    delete:
      $ref: '../swagger/path/contacts/id/delete.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
